const BASE_URL = `http://localhost:8080`;

export const CONCEPT = `${BASE_URL}/concept`;
export const CONCEPT_NAME = `${BASE_URL}/conceptname`;
export const CONCEPT_CLASS = `${BASE_URL}/conceptclass`;
export const CONCEPT_DATA_TYPE = `${BASE_URL}/conceptdatatype`;
export const CONCEPT_MAP_TYPE = `${BASE_URL}/conceptmaptype`;
export const CONCEPT_REFERENCE_SOURCE = `${BASE_URL}/conceptreferencesource`;
export const CONCEPT_REFERENCE_TERM = `${BASE_URL}/conceptreferenceterm`;
export const DRUG = `${BASE_URL}/drug`;
export const PATIENT_RELATIONSHIP_TYPE = `${BASE_URL}/relationshiptype`;
export const PRIVILEGE = `${BASE_URL}/privilege`;
export const VISIT_TYPE = `${BASE_URL}/visittype`;
export const PERSON_NAME = `${BASE_URL}/personname`;
export const PERSON = `${BASE_URL}/person`;
export const PERSON_ATTRIBUTE_TYPE = `${BASE_URL}/personattributetype`;
export const USER = `${BASE_URL}/users`;
export const ADDRESS_HIERARCHY_LEVEL = `${BASE_URL}/addresshierarchylevel`;
export const ROLE = `${BASE_URL}/role`;
